### ISSUE TITLE
Abgleich der Modellanforderungen mit einer Vorlage

### ISSUE THREAD

**Issue by FroPsu** [c-mellueh/SOM-Toolkit#21]
Die Modellanforderungen werden u. a. projektspezifisch angepasst. Aus meiner Sicht wäre es hilfreich zwei verschiedene Versionen/Stände von diesen Modellanforderungen abzugleichen, d. h. ein Versionsvergleich durchzuführen. So lassen sich bspw. projektspezifische Anpassungen schnell herausfinden bzw. lassen sich Unterschiede zu älteren Versionen nachvollziehen.

**Comment by c-mellueh** [comment]
done in #162
